# Generated by Django 3.2.9 on 2021-11-23 00:49

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(default=api.models.unique_id, editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('desciption', models.TextField()),
            ],
        ),
    ]
