# Generated by Django 3.2.9 on 2021-12-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_chat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
