# Generated by Django 3.2.9 on 2021-11-23 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211123_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='radius',
            field=models.IntegerField(null=True),
        ),
    ]
