# Generated by Django 3.2.9 on 2021-11-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_chat_radius'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='radius',
            field=models.IntegerField(default=1),
        ),
    ]
