# Generated by Django 3.2.9 on 2021-11-23 01:20

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_chat_radius'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
    ]
