# Generated by Django 3.2.9 on 2021-11-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211123_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
