# Generated by Django 3.2.9 on 2021-11-23 03:34

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_directchat_directmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0), geography=True, srid=4326),
        ),
        migrations.AddField(
            model_name='chat',
            name='radius',
            field=models.IntegerField(default=5),
        ),
    ]
