# Generated by Django 3.2.9 on 2021-11-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_chat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='radius',
            field=models.FloatField(default=5),
        ),
    ]
