# Generated by Django 3.2.9 on 2021-11-23 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_desciption_chat_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directmessage',
            name='reciever',
        ),
    ]
