# Generated by Django 3.2.9 on 2021-11-23 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_directmessage_reciever'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='sender',
        ),
    ]
