# Generated by Django 3.2.9 on 2021-11-23 08:02

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20211123_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='message_id',
            field=models.CharField(default=api.models.unique_id, editable=False, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='message',
            name='message_id',
            field=models.CharField(default=api.models.unique_id, editable=False, max_length=10, unique=True),
        ),
    ]
