# Generated by Django 3.2.9 on 2021-11-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_directmessagelike_messagelike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
