# Generated by Django 3.2.9 on 2021-11-29 19:37

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20211123_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.get_file_path),
        ),
    ]
