# Generated by Django 3.2.9 on 2021-11-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20211129_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='location',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='polygon',
        ),
        migrations.AddField(
            model_name='chat',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='chat',
            name='long',
            field=models.FloatField(default=0),
        ),
    ]
